# Add activity_log table for recent activities
# Table: activity_log
# Columns: id (uuid, pk), business_id (uuid), user_id (uuid), type (text), description (text), employee_id (uuid, nullable), created_at (timestamp, default now()), metadata (jsonb, nullable)

[functions.send-onboarding-email]
enabled = true
verify_jwt = true
import_map = "./functions/send-onboarding-email/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-onboarding-email/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-onboarding-email/*.html" ]
